import type { UiLocale } from '@/lib/i18n';

export const earlyBirdCopy = {
    es: {
        eyebrow: 'EARLYBIRDS · ACCESO FUNDADOR',
        title: 'El Beacon, siempre presente.',
        intro: 'Una línea temporal compartida, disponible las 24 horas para volver a escuchar, respirar y entrar.',
        live: 'Beacon 24/7',
        privateDropIns: 'Drop-ins privados completos en español e inglés',
        membership: 'Membresía fundadora · US$2 por mes',
        signInGoogle: 'Continuar con Google',
        signInApple: 'Continuar con Apple',
        signingIn: 'Abriendo acceso…',
        providerSoon: 'Configuración pendiente',
        signedIn: 'Tu cuenta EarlyBird está lista.',
        enter: 'Entrar al Beacon',
        redeem: 'Activar mi invitación',
        accessNeeded: 'Tu cuenta todavía no tiene una membresía activa.',
        authError: 'No pudimos completar el acceso. Usa el mismo proveedor con el que creaste tu cuenta o contacta a soporte.',
        privacy: 'Tu cuenta y membresía administran el acceso a EarlyBirds. No creamos historiales personales de escucha.',
    },
    en: {
        eyebrow: 'EARLYBIRDS · FOUNDING ACCESS',
        title: 'The Beacon, always present.',
        intro: 'One shared timeline, available around the clock whenever you want to listen, breathe, and enter.',
        live: 'Beacon 24/7',
        privateDropIns: 'Complete private drop-ins in Spanish and English',
        membership: 'Founding membership · US$2 per month',
        signInGoogle: 'Continue with Google',
        signInApple: 'Continue with Apple',
        signingIn: 'Opening access…',
        providerSoon: 'Configuration pending',
        signedIn: 'Your EarlyBird account is ready.',
        enter: 'Enter the Beacon',
        redeem: 'Activate my invitation',
        accessNeeded: 'Your account does not have an active membership yet.',
        authError: 'We could not complete sign-in. Use the provider that created your account, or contact support.',
        privacy: 'Your account and membership manage access to EarlyBirds. We do not create personal listening histories.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdSyntheticEntryCopy = {
    es: {
        title: 'Acceso de equipo · staging',
        description: 'Sólo para pruebas acordadas. Usa una cuenta sintética @e2e.invalid y el código temporal del equipo.',
        name: 'Nombre de prueba',
        email: 'Cuenta sintética',
        accessCode: 'Código de acceso temporal',
        enter: 'Entrar a staging',
        entering: 'Abriendo staging…',
        failed: 'El acceso de prueba no está disponible o los datos no son válidos.',
    },
    en: {
        title: 'Team access · staging',
        description: 'For agreed testing only. Use a synthetic @e2e.invalid account and the team’s temporary access code.',
        name: 'Test name',
        email: 'Synthetic account',
        accessCode: 'Temporary access code',
        enter: 'Enter staging',
        entering: 'Opening staging…',
        failed: 'Test access is unavailable or the supplied details are invalid.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdHomeCopy = {
    es: {
        eyebrow: 'EARLYBIRDS · LISTENER',
        heading: 'Beacon 24/7',
        sharedPoint: 'Punto compartido',
        subheading: 'Estás entrando al mismo punto del Beacon continuo grabado que todas las personas EarlyBird.',
        play: 'Escuchar ahora',
        pause: 'Pausar',
        resume: 'Volver al presente',
        loading: 'Conectando…',
        reconnecting: 'Restableciendo conexión…',
        unavailable: 'El Beacon no está disponible en este momento.',
        displaced: 'Este dispositivo fue desplazado porque la cuenta ya está escuchando en otros dos dispositivos.',
        dropIns: 'Drop-ins privados',
        spanish: 'Caldeamiento · Español',
        english: 'Warm-up · English',
        dropUnavailable: 'El render aprobado todavía no fue publicado.',
        dropPlay: 'Reproducir',
        restart: 'Reiniciar',
        master: 'Volumen master',
        signOut: 'Cerrar sesión',
        active: 'Membresía activa',
    },
    en: {
        eyebrow: 'EARLYBIRDS · LISTENER',
        heading: 'Beacon 24/7',
        sharedPoint: 'Shared point',
        subheading: 'You are joining the same point in the continuous recorded Beacon as every other EarlyBird listener.',
        play: 'Listen now',
        pause: 'Pause',
        resume: 'Return to now',
        loading: 'Connecting…',
        reconnecting: 'Restoring connection…',
        unavailable: 'The Beacon is unavailable right now.',
        displaced: 'This device was displaced because the account is already listening on two other devices.',
        dropIns: 'Private drop-ins',
        spanish: 'Warm-up · Spanish',
        english: 'Warm-up · English',
        dropUnavailable: 'The approved render has not been published yet.',
        dropPlay: 'Play',
        restart: 'Restart',
        master: 'Master volume',
        signOut: 'Sign out',
        active: 'Active membership',
    },
} satisfies Record<UiLocale, Record<string, string>>;
