import type { UiLocale } from '@/lib/i18n';

export const earlyBirdCopy = {
    es: {
        eyebrow: 'EARLYBIRDS · ACCESO FUNDADOR',
        title: 'El Beacon, siempre presente.',
        intro: 'Una línea temporal compartida, disponible las 24 horas para volver a escuchar, respirar y entrar.',
        live: 'Beacon 24/7',
        privateDropIns: 'Drop-ins privados completos en español e inglés',
        membership: 'Membresía fundadora · US$2 por mes',
        signInGoogle: 'Continuar con Google',
        signInApple: 'Continuar con Apple',
        signingIn: 'Abriendo acceso…',
        providerSoon: 'Configuración pendiente',
        signedIn: 'Tu cuenta EarlyBird está lista.',
        enter: 'Entrar al Beacon',
        redeem: 'Activar mi invitación',
        accessNeeded: 'Tu cuenta todavía no tiene una membresía activa.',
        authError: 'No pudimos completar el acceso. Usa el mismo proveedor con el que creaste tu cuenta o contacta a soporte.',
        privacy: 'La cuenta, la membresía y el pago pertenecen a una persona adulta. No creamos perfiles de menores ni historiales personales de escucha.',
    },
    en: {
        eyebrow: 'EARLYBIRDS · FOUNDING ACCESS',
        title: 'The Beacon, always present.',
        intro: 'One shared timeline, available around the clock whenever you want to listen, breathe, and enter.',
        live: 'Beacon 24/7',
        privateDropIns: 'Complete private drop-ins in Spanish and English',
        membership: 'Founding membership · US$2 per month',
        signInGoogle: 'Continue with Google',
        signInApple: 'Continue with Apple',
        signingIn: 'Opening access…',
        providerSoon: 'Configuration pending',
        signedIn: 'Your EarlyBird account is ready.',
        enter: 'Enter the Beacon',
        redeem: 'Activate my invitation',
        accessNeeded: 'Your account does not have an active membership yet.',
        authError: 'We could not complete sign-in. Use the provider that created your account, or contact support.',
        privacy: 'An adult owns the account, membership, consent, and payment. We do not create child profiles or personal listening histories.',
    },
} satisfies Record<UiLocale, Record<string, string>>;

export const earlyBirdHomeCopy = {
    es: {
        eyebrow: 'EARLYBIRDS · LISTENER',
        heading: 'Beacon 24/7',
        subheading: 'Estás entrando al mismo borde vivo que todas las personas EarlyBird.',
        play: 'Escuchar en vivo',
        pause: 'Pausar',
        resume: 'Volver al borde vivo',
        loading: 'Conectando…',
        unavailable: 'El Beacon no está disponible en este momento.',
        displaced: 'Este dispositivo fue desplazado porque la cuenta ya está escuchando en otros dos dispositivos.',
        dropIns: 'Drop-ins privados',
        spanish: 'Caldeamiento · Español',
        english: 'Warm-up · English',
        dropUnavailable: 'El render aprobado todavía no fue publicado.',
        restart: 'Reiniciar',
        master: 'Volumen master',
        signOut: 'Cerrar sesión',
        active: 'Membresía activa',
    },
    en: {
        eyebrow: 'EARLYBIRDS · LISTENER',
        heading: 'Beacon 24/7',
        subheading: 'You are joining the same live edge as every other EarlyBird listener.',
        play: 'Listen live',
        pause: 'Pause',
        resume: 'Return to live edge',
        loading: 'Connecting…',
        unavailable: 'The Beacon is unavailable right now.',
        displaced: 'This device was displaced because the account is already listening on two other devices.',
        dropIns: 'Private drop-ins',
        spanish: 'Warm-up · Spanish',
        english: 'Warm-up · English',
        dropUnavailable: 'The approved render has not been published yet.',
        restart: 'Restart',
        master: 'Master volume',
        signOut: 'Sign out',
        active: 'Active membership',
    },
} satisfies Record<UiLocale, Record<string, string>>;
